name: Habit_Tracker
dependencies:
  - python = 3.13
  - django = 5.1.*
  - conda-forge::selenium = 4.*
  - conda-forge::django-stubs-ext
  - pip
  - pip:
    - django-types
  - conda-forge::types-requests