# Generated by Django 5.1.7 on 2025-04-01 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_habit_tracker", "0002_alter_habittrackeruser_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="user",
            new_name="owner",
        ),
    ]
